# -*- coding: utf-8 -*-
"""craters-gs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wQEMrar1fAmRQu9UxdBrNUFZV26CmSe5
"""

r"""2d gaussian mixture for images."""
from collections.abc import Generator

import torch
from torch import Size, Tensor, nn
from torch.optim import Adam
import sys
from IPython import display


class GaussianSplats(nn.Module):
    r"""Gaussian Splatting modules for Image rendering."""

    def __init__(self, n_gaussians: int, n_channels: int = 3) -> None:
        r"""Initialize gaussians."""
        super().__init__()
        self.n_gaussians= n_gaussians
        self.n_channels = None # Assuming RGB colors
        self.alpha_channel = False #future option

        # Initialize the parameters of the Gaussian components
        self.centers = nn.Parameter(2*torch.rand(n_gaussians, 2)-1)
        self.covs = nn.Parameter(torch.randn(n_gaussians, 3).abs()) # (a, b, \theta)
        self._colors = nn.Parameter(torch.randn(n_gaussians, n_channels))
        self._alphas = nn.Parameter(torch.randn(n_gaussians)) # The alpha values for each ellipse
        self.img_size = None

    @property
    def colors(self)-> nn.Parameter:
        r"""Return colors defined between 0 and 1."""
        #return self._colors.sigmoid()
        self._colors.data= self._colors.clip(0,1)
        return self._colors
    @property
    def alphas(self)->nn.Parameter:
        r"""Return transparency defined between 0 and 1."""
        #return self._alphas.sigmoid() # slow down gradient
        self._alphas.data= self._alphas.clip(0,1)
        return self._alphas

    def _splats_init(self):
      self.centers
    def forward(self, img_size: Size | None = None)-> Tensor:
        r"""Reconstruct the image based on the Gaussians parameters."""
        img_size = self.img_size if img_size is None else img_size
        assert img_size is not None, "Provide an image size or fit before rendering"
        x ,y = torch.linspace(-1,1, img_size[0]), torch.linspace(-1,1, img_size[1])
        x, y = x.to(self.centers.device), y.to(self.centers.device)
        xx, yy = torch.meshgrid(x, y)
        xx = xx.unsqueeze(0).repeat(self.n_gaussians,1,1)
        yy = yy.unsqueeze(0).repeat(self.n_gaussians,1,1)
        # Centering
        xx = xx - self.centers[:,0, None, None]
        yy = yy - self.centers[:,1, None, None]
        # Apply rotation
        theta = self.covs[:,0, None, None]
        rot_xx = xx*theta.cos() - yy*theta.sin()
        rot_yy = xx*theta.sin() + yy*theta.cos()
        # Apply anisotropic scaling
        inv_a = 1/(self.covs[:,2].abs()+1e-7)[:,None,None]
        inv_b = 1/(self.covs[:,1].abs()+1e-7)[:,None,None]
        zz = (rot_xx*inv_a)**2 + (rot_yy*inv_b)**2
        gs = torch.exp(-0.5 * zz)
        gs = gs.unsqueeze(1) # prepares for channels wise multiplication
        alphas = self.alphas[:,None,None,None]
        colors = self.colors[:,:,None,None]
        return (colors*gs*alphas).sum(0)/(gs*alphas).sum(0)

    def _fit_iterable(self, img:Tensor, n_iters:int = 100, get_pil=False)->Generator[Tensor]:
        r"""Fit the Gaussian parameters to the input image and return intermediate.

        Args:
            img (Tensor): The input image tensor of shape (C, H, W).
        """
        self.img_size = img.shape[1:]
        assert self.colors.shape[-1] == img.shape[0], "Colors mismatch."
        optim=Adam([self.centers, self.covs, self._colors, self._alphas], lr=0.05)
        schedulerr = torch.optim.lr_scheduler.CosineAnnealingLR(optim, T_max=n_iters)
        for _ in range(n_iters):
            rendered = self.forward()
            err = torch.nn.MSELoss()(rendered,img)
            sys.stdout.write(f"\rIteration {_}, Fitting error: {err.item()}")
            sys.stdout.flush()
            if get_pil:
              rendered = tf.to_pil_image(rendered.to("cpu").detach())
            yield rendered, err.cpu()
            err.backward()
            optim.step()
            optim.zero_grad()
            schedulerr.step()

    def fit(self,img:Tensor, n_iters:int = 100)->None:
        r"""Fit the Gaussian parameters to the image."""
        for i, _ in enumerate(self._fit_iterable(img, n_iters)):
            sys.stdout.write(f"\rIteration {i}")
        print("Done.")

r"""Visualize splats and fitting error."""
from argparse import ArgumentParser

import torch
import torchvision.transforms.functional as tf
from PIL import Image
from torch import Tensor


def import_image_as_tensor(img_path: str)-> Tensor:
    r"""Import image as tensor."""
    img = Image.open(img_path).convert("RGB")
    return tf.to_tensor(img)


img_path = "gauss.jpeg"
n_gaussians=2240
n_iters=200
out_path="splat_rendering.gif"

device = torch.device("cpu")
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    print("Using GPU for fitting.")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
    print("Using MPS for fitting.")

img = import_image_as_tensor(img_path).to(device)
# reduce image to 224
img = tf.resize(img, (224))
print("Fitting...")
print(f"Compression ratio: {9*n_gaussians/img.numel()}")
model = GaussianSplats(n_gaussians=n_gaussians, n_channels=3).to(device)
#iters = list(model._fit_iterable(img, n_iters=n_iters))
#frames = [tf.to_pil_image(it[0].to("cpu")) for it in iters]
 # Save gif from list
frames_gen=model._fit_iterable(img, n_iters=n_iters, get_pil=True)
frames= map(lambda x: x[0], frames_gen)
next(frames).save(out_path, save_all=True, append_images=frames,
                duration=n_iters//30)
display.Image("splat_rendering.gif")

## Evaluate the mse, ratio curve
import matplotlib.pyplot as plt

ratio = torch.logspace(-3,-1,20)
psnrs=[]
for r in ratio:
  n_gaussians = int(img.numel()*r/9)
  print(n_gaussians)
  model = GaussianSplats(n_gaussians=n_gaussians, n_channels=3).to(device)
  try:
    model.fit(img, n_iters = 500)
  except:
    break
  rendered = model()
  err = torch.nn.MSELoss()(img, rendered).cpu().detach()
  PSNR = 10*torch.log10(1/err)
  psnrs.append(PSNR)
plt.plot(ratio, psnrs)
plt.show()

torch.logspace(-4,-3,20)

next(frames)

